In [1]:
import math
import numpy as np

In [2]:
# Настроим количество отображаемых десятичных знаков
np.set_printoptions(precision=2, suppress=True)

In [3]:
# Инициируем матрицу
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [9]:
# Выполним сингуля́рное разложение матрицы (SVD)
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# Определим список диагональных элементов s
D = np.zeros_like(A, dtype=float)

# Выделим диагональные элементы s
D[np.diag_indices(min(A.shape))] = s

print(f'Матрица D:\n{D}')
print(f'\nМатрица U:\n{U}')
print(f'\nМатрица V:\n{V}')

# Проверим, верно ли выполнено SVD, перемножив матрицы по формуле
print(f'\nИсходная матрица (проверка):\n {np.dot(np.dot(U, D), V.T)}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]

Исходная матрица (проверка):
 [[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


In [6]:
# Найдем евклидову норму – максимальное число из диагональных
print(f'Евклидова норма: {max(s)}')

Евклидова норма: 8.824868854820442


In [10]:
# Найдем норму Фробениуса – корень квадратный из суммы квадратов диаональных элементов
sum_kv = 0
for num in s:
    sum_kv += num**2
print(f'Норма Фробениуса: {math.sqrt(sum_kv)}')

Норма Фробениуса: 11.045361017187261
